// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @shoebox/photo
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.uint.preencode(state, m.takenAt)
    c.string.preencode(state, m.mime)
    c.uint.preencode(state, m.byteLength)
    c.fixed32.preencode(state, m.blobsCoreKey)
    c.uint.preencode(state, m.blockOffset)
    c.uint.preencode(state, m.blockLength)
    c.uint.preencode(state, m.byteOffset)
    c.uint.preencode(state, m.blobByteLength)
    state.end++ // max flag is 8 so always one byte

    if (m.width) c.uint.preencode(state, m.width)
    if (m.height) c.uint.preencode(state, m.height)
    if (m.orientation) c.uint.preencode(state, m.orientation)
    if (m.thumb) c.string.preencode(state, m.thumb)
  },
  encode(state, m) {
    const flags =
      (m.width ? 1 : 0) | (m.height ? 2 : 0) | (m.orientation ? 4 : 0) | (m.thumb ? 8 : 0)

    c.string.encode(state, m.name)
    c.uint.encode(state, m.takenAt)
    c.string.encode(state, m.mime)
    c.uint.encode(state, m.byteLength)
    c.fixed32.encode(state, m.blobsCoreKey)
    c.uint.encode(state, m.blockOffset)
    c.uint.encode(state, m.blockLength)
    c.uint.encode(state, m.byteOffset)
    c.uint.encode(state, m.blobByteLength)
    c.uint.encode(state, flags)

    if (m.width) c.uint.encode(state, m.width)
    if (m.height) c.uint.encode(state, m.height)
    if (m.orientation) c.uint.encode(state, m.orientation)
    if (m.thumb) c.string.encode(state, m.thumb)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.fixed32.decode(state)
    const r5 = c.uint.decode(state)
    const r6 = c.uint.decode(state)
    const r7 = c.uint.decode(state)
    const r8 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      name: r0,
      takenAt: r1,
      mime: r2,
      byteLength: r3,
      blobsCoreKey: r4,
      blockOffset: r5,
      blockLength: r6,
      byteOffset: r7,
      blobByteLength: r8,
      width: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      height: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      orientation: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      thumb: (flags & 8) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@shoebox/photo':
      return encoding0
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
